spring-cloud/spring-cloud-deployer

- spring-cloud-deployer-spi-test/pom.xml
- spring-cloud-deployer-spi-test/src/main/java/org/springframework/cloud/deployer/spi/test/AbstractAppDeployerIntegrationTests.java
Fixes spring-cloud/spring-cloud-deployer#13
> Don't assume Maven for the deployed test apps.

- spring-cloud-deployer-resource-maven/src/main/java/org/springframework/cloud/deployer/resource/maven/MavenResource.java
- spring-cloud-deployer-resource-maven/src/main/java/org/springframework/cloud/deployer/resource/maven/MavenResourceLoader.java
- spring-cloud-deployer-resource-maven/src/test/java/org/springframework/cloud/deployer/resource/maven/MavenResourceLoaderTests.java
Resolves spring-cloud/spring-cloud-dataflow#403
> add MavenResourceLoader

- spring-cloud-deployer-spi-test-app/pom.xml
- changing to use new official image java:8-alpine
- changing to use springcloud account instead of springcloudstream since this isn't stream related
> Updating Docker image

- spring-cloud-deployer-resource-support/src/main/java/org/springframework/cloud/deployer/resource/registry/UriRegistryPopulator.java
- spring-cloud-deployer-resource-support/src/test/java/org/springframework/cloud/deployer/resource/registry/UriRegistryPopulatorTests.java
required by https://github.com/spring-cloud/spring-cloud-dataflow/pull/549
> add overwrite boolean param to registry populator

- spring-cloud-deployer-resource-maven/src/test/java/org/springframework/cloud/deployer/resource/maven/MavenResourceTests.java
- spring-cloud-deployer-resource-support/src/test/java/org/springframework/cloud/deployer/resource/registry/UriRegistryPopulatorTests.java
- spring-cloud-deployer-sample-stream/src/main/java/sample/TickTock.java
- spring-cloud-deployer-sample-task/src/main/java/sample/TimeStamp.java
> updating resources for starter apps

- spring-cloud-deployer-spi-test-app/src/main/java/org/springframework/cloud/deployer/spi/test/app/DeployerIntegrationTest.java
- spring-cloud-deployer-spi-test-app/src/main/java/org/springframework/cloud/deployer/spi/test/app/DeployerIntegrationTestProperties.java
> Add exit code property to be used for task tests

- spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/AbstractLocalDeployerSupport.java
- spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/LocalAppDeployer.java
- spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/LocalTaskLauncher.java
- spring-cloud-deployer-spi/src/main/java/org/springframework/cloud/deployer/spi/app/AppDeployer.java
- spring-cloud-deployer-spi/src/main/java/org/springframework/cloud/deployer/spi/core/AppDeploymentRequest.java
> environmentProperties now deploymentProperties

- spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/LocalAppDeployer.java
> do not pass deployment props to the app

- spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/LocalAppDeployer.java
- spring-cloud-deployer-spi-test/src/main/java/org/springframework/cloud/deployer/spi/test/AbstractAppDeployerIntegrationTests.java
Also, have a better default name for deployed apps in tests
> Fix LocalDeployer to fail faster in status()

- spring-cloud-deployer-spi-test/src/main/java/org/springframework/cloud/deployer/spi/test/AbstractAppDeployerIntegrationTests.java
Fixes spring-cloud/spring-cloud-deployer#102
> Honor MavenProperties in TCK

- spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/LocalDeployerProperties.java
> Fix local deployer log config property

- pom.xml
- update to Spring Framework 4.3.3
Resolves #108
> Update to use Brixton.SR6

- pom.xml
- spring-cloud-deployer-resource-maven/src/main/java/org/springframework/cloud/deployer/resource/maven/MavenArtifactResolver.java
Fixes https://github.com/spring-cloud/spring-cloud-deployer/issues/114
> Upgrade to Spring Cloud Camden

- pom.xml
- spring-cloud-deployer-local/pom.xml
- spring-cloud-deployer-local/src/test/java/org/springframework/cloud/deployer/spi/local/LocalAppDeployerIntegrationTests.java
- spring-cloud-deployer-local/src/test/java/org/springframework/cloud/deployer/spi/local/LocalTaskLauncherIntegrationTests.java
- spring-cloud-deployer-resource-docker/pom.xml
- spring-cloud-deployer-resource-maven/pom.xml
- spring-cloud-deployer-resource-support/pom.xml
- spring-cloud-deployer-sample-stream/pom.xml
- spring-cloud-deployer-sample-task/pom.xml
- spring-cloud-deployer-spi-test-app/pom.xml
- spring-cloud-deployer-spi-test/pom.xml
- spring-cloud-deployer-spi-test/src/main/java/org/springframework/cloud/deployer/spi/test/AbstractIntegrationTests.java
- spring-cloud-deployer-spi/pom.xml
Also, bump version to 1.1.0.BUILD-SNAPSHOT.
Fixes https://github.com/spring-cloud/spring-cloud-deployer/issues/114
> Update to Camden spring cloud build.

- spring-cloud-deployer-spi/src/main/java/org/springframework/cloud/deployer/spi/util/CommandLineTokenizer.java
- spring-cloud-deployer-spi/src/test/java/org/springframework/cloud/deployer/spi/util/CommandLineTokenizerTests.java
Fixes https://github.com/spring-cloud/spring-cloud-deployer/issues/133
> Fix tokenizing bug when delimiter is space

- spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/LocalDeployerProperties.java
Resolves spring-cloud/spring-cloud-deployer#120
> GH-120 Add PATH to list of inherited env-vars in launched process

- spring-cloud-deployer-spi-test/src/main/java/org/springframework/cloud/deployer/spi/test/AbstractIntegrationTests.java
Fixes https://github.com/spring-cloud/spring-cloud-deployer/issues/144
> Fix abstract IT to actually use its config

- README.adoc
> Update README to include recent changes

- pom.xml
- spring-cloud-deployer-spi/src/main/java/org/springframework/cloud/deployer/spi/task/TaskLauncher.java
> Revert deployer SPI to be compatible with Java 1.7

- .mvn/wrapper/maven-wrapper.properties
- pom.xml
> Update to Camden SR3 and maven wrapper 3.3.9

- spring-cloud-deployer-resource-maven/src/main/java/org/springframework/cloud/deployer/resource/maven/MavenArtifactResolver.java
Fixes https://github.com/spring-cloud/spring-cloud-deployer/issues/189
> Double check m2 repo directory creation

- spring-cloud-deployer-spi-test/src/main/java/org/springframework/cloud/deployer/spi/test/AbstractAppDeployerIntegrationTests.java
- spring-cloud-deployer-spi-test/src/main/java/org/springframework/cloud/deployer/spi/test/AbstractIntegrationTests.java
- spring-cloud-deployer-spi-test/src/main/java/org/springframework/cloud/deployer/spi/test/AbstractTaskLauncherIntegrationTests.java
Fixes https://github.com/spring-cloud/spring-cloud-deployer/issues/195
**To be co-ordinated with the PRs referenced below**
https://github.com/spring-cloud/spring-cloud-deployer-local/pull/21
https://github.com/spring-cloud/spring-cloud-deployer-mesos/pull/52
https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/pull/108
https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/pull/158
> Make sure to cleanup created resources after tests

- spring-cloud-deployer-spi/src/main/java/org/springframework/cloud/deployer/spi/app/DeployerEnvironmentInfo.java
- spring-cloud-deployer-spi/src/test/java/org/springframework/cloud/deployer/spi/app/DeployerEnvironmentInfoBuilderTests.java
> Add deployerName and platformApiVersion to DeployerEnvironmentInfo

- spring-cloud-deployer-resource-maven/src/main/java/org/springframework/cloud/deployer/resource/maven/MavenArtifactResolver.java
> Improve error message for maven repository location

- pom.xml
> Update spring-cloud-build and spring versions

- spring-cloud-deployer-spi-test-app/src/main/java/org/springframework/cloud/deployer/spi/test/app/DeployerIntegrationTestProperties.java
- Simply adding option to get instance.index as well.
- Fixes #250
> Enhance test app not to force INSTANCE_INDEX

- spring-cloud-deployer-resource-support/src/main/java/org/springframework/cloud/deployer/resource/support/DownloadingUrlResource.java
- spring-cloud-deployer-resource-support/src/test/java/org/springframework/cloud/deployer/resource/support/DownloadingUrlResourceTests.java
> Rename artifact downloaded by DownloadingUrlResource

- spring-cloud-deployer-spi/src/main/java/org/springframework/cloud/deployer/spi/app/MultiStateAppDeployer.java
> Undeprecate MultiStateAppDeployer

- spring-cloud-deployer-spi/src/main/java/org/springframework/cloud/deployer/spi/app/AppScaleRequest.java
- to Optional<Map<String,String>> properties
> Update AppScaleRequest's properties signature

- spring-cloud-deployer-spi/pom.xml
- spring-cloud-deployer-spi/src/main/java/org/springframework/cloud/deployer/spi/app/AppDeployer.java
- spring-cloud-deployer-spi/src/main/java/org/springframework/cloud/deployer/spi/app/MultiStateAppDeployer.java
- New methods statusReactive where we can pass in multiple
id's getting status back with one request.
- Fixes #336
> Add reactive status methods

- spring-cloud-deployer-resource-maven/src/main/java/org/springframework/cloud/deployer/resource/maven/MavenArtifactResolver.java
- spring-cloud-deployer-resource-maven/src/main/java/org/springframework/cloud/deployer/resource/maven/MavenResource.java
- spring-cloud-deployer-resource-maven/src/test/java/org/springframework/cloud/deployer/resource/maven/MavenResourceTests.java
- Use Maven artifact resolver to retrieve versions of the maven artifact
- Add test
Resolves #343
> Get versions on maven resource

- spring-cloud-deployer-spi-test/pom.xml
- spring-cloud-deployer-spi-test/src/main/java/org/springframework/cloud/deployer/spi/scheduler/test/AbstractSchedulerIntegrationJUnit5Tests.java
- spring-cloud-deployer-spi-test/src/main/java/org/springframework/cloud/deployer/spi/test/AbstractAppDeployerIntegrationJUnit5Tests.java
- spring-cloud-deployer-spi-test/src/main/java/org/springframework/cloud/deployer/spi/test/AbstractIntegrationJUnit5Tests.java
- spring-cloud-deployer-spi-test/src/main/java/org/springframework/cloud/deployer/spi/test/AbstractTaskLauncherIntegrationJUnit5Tests.java
- This is a prep work to move away from junit4
- Fixes #346
> Create spi base classes for junit5

- pom.xml
> build: update maven-wagon 3.5.2.

- .github/settings.xml
- .settings.xml
- pom.xml
- spring-cloud-deployer-dependencies/pom.xml
See https://github.com/spring-cloud/spring-cloud-dataflow/issues/5193
> Add MavenCentral in place of repo.spring.io/release (#101)

- .github/settings.xml
- .settings.xml
- pom.xml
- spring-cloud-deployer-dependencies/pom.xml
See https://github.com/spring-cloud/spring-cloud-dataflow/issues/5193
> Set snapshot=false on Maven Central repos

- spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesDeployerProperties.java
- spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesScheduler.java
- spring-cloud-deployer-kubernetes/src/test/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesSchedulerIT.java
See https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/407
> Add backoffLimit to KubernetesScheduler

- .settings.xml
- pom.xml
- spring-cloud-deployer-dependencies/pom.xml
- spring-cloud-deployer-resource-maven/src/test/java/org/springframework/cloud/deployer/resource/maven/MavenResourceTests.java
See spring-cloud/spring-cloud-dataflow#5325
> Switch Maven repos off of libs-* variants

- spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/DeploymentPropertiesResolver.java
- spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesDeployerProperties.java
- spring-cloud-deployer-kubernetes/src/test/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesAppDeployerTests.java
> Correct spelling for terminationGracePeriodSeconds

- spring-cloud-deployer-cloudfoundry/pom.xml
> Update commons-compress to 1.24.0

- pom.xml
> Bump Dependencies to Spring Boot 2.7.18

- .github/workflows/release-worker.yml
See https://github.com/spring-cloud/spring-cloud-dataflow/issues/5584
> Use new private release repo libs-release-staging

- spring-cloud-deployer-cloudfoundry/src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/ApplicationLogAccessor.java
This will give users more visibility into their logs
> Increase log envelope limit to the max allowable.

- .github/workflows/ci-it.yml
- spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/DeploymentPropertiesResolver.java
- spring-cloud-deployer-kubernetes/src/test/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesAppDeployerIntegrationIT.java
> Restore init container fixes.

- pom.xml
> Update json-path to 2.9.0

- .editorconfig
- .github/workflows/ci-pr.yml
- .github/workflows/ci.yml
- pom.xml
- spring-cloud-deployer-cloudfoundry/src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryActuatorTemplateTests.java
- spring-cloud-deployer-kubernetes/pom.xml
- spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/AbstractKubernetesDeployer.java
- spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesAppDeployer.java
- spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesScheduler.java
- spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesTaskLauncher.java
- spring-cloud-deployer-kubernetes/src/test/java/org/springframework/cloud/deployer/spi/kubernetes/AbstractKubernetesTaskLauncherIntegrationTests.java
- spring-cloud-deployer-kubernetes/src/test/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesAppDeployerIntegrationIT.java
- spring-cloud-deployer-kubernetes/src/test/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesConfigurationPropertiesTests.java
- spring-cloud-deployer-kubernetes/src/test/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesSchedulerIT.java
- spring-cloud-deployer-resource-maven/src/test/java/org/springframework/cloud/deployer/resource/maven/MavenExtension.java
- spring-cloud-deployer-resource-maven/src/test/java/org/springframework/cloud/deployer/resource/maven/WagonHttpTests.java
- spring-cloud-deployer-spi-scheduler-test-app/pom.xml
- spring-cloud-deployer-spi-test/src/main/java/org/springframework/cloud/deployer/spi/scheduler/test/AbstractSchedulerIntegrationJUnit5Tests.java
- src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- src/test/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesTaskLauncherIntegrationIT.java
Update Fabric8 version and usage.
Added version for json-path 2.9.0
Unit Tests and ITs pass locally
> Update Fabric8 version and usage.

- pom.xml
- spring-cloud-deployer-cloudfoundry/pom.xml
Update Commons Compress to 1.26.0
> Update Spring Boot to 3.2.5

- pom.xml
- spring-cloud-deployer-cloudfoundry/pom.xml
Also update the following:
* Update to commons-compress 1.26.2
* Update cloudfoundry-client-reactor to 5.12.1.RELEASE
> Update Spring Boot to 3.3.0

- .github/workflows/build-snapshot-worker.yml
- .github/workflows/ci-it.yml
- .github/workflows/ci-pr.yml
- .github/workflows/ci.yml
- .github/workflows/issue-handler.yml
- .github/workflows/milestone-worker.yml
- .github/workflows/next-dev-version-worker.yml
- .github/workflows/release-worker.yml
- .mvn/wrapper/maven-wrapper.properties
- spring-cloud-deployer-kubernetes/pom.xml
- spring-cloud-deployer-spi-test-app/pom.xml
* Remove setup-maven. 
* Fix main-3 references. 
* Bump maven plugin versions.
> Update CI after main-3 merge.

- spring-cloud-deployer-cloudfoundry/src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/AbstractCloudFoundryDeployer.java
- spring-cloud-deployer-cloudfoundry/src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CfEnvAwareResource.java
- spring-cloud-deployer-cloudfoundry/src/main/java/org/springframework/cloud/deployer/spi/scheduler/cloudfoundry/expression/QuartzCronExpression.java
- spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/AbstractKubernetesDeployer.java
- spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/DefaultContainerFactory.java
- spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/DeploymentPropertiesResolver.java
- spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesAppDeployer.java
- spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesTaskLauncher.java
- spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/support/RelaxedNames.java
- spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/LocalDeployerUtils.java
- spring-cloud-deployer-local/src/test/java/org/springframework/cloud/deployer/spi/local/LocalAppDeployerEnvironmentIntegrationTests.java
- src/main/java/org/springframework/cloud/deployer/spi/kubernetes/DefaultContainerFactory.java
- src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesAppDeployer.java
- src/main/java/org/springframework/cloud/deployer/spi/local/LocalDeployerUtils.java
- src/test/java/org/springframework/cloud/deployer/spi/local/LocalAppDeployerEnvironmentIntegrationTests.java
Update `toLowerCase` and `toUpperCase` to use `Locale.ROOT`
> Update toLowerCase and toUpperCase to use Locale.ROOT

- .github/workflows/ci-pr.yml
- .github/workflows/ci.yml
Adds environment variables allowing trivy to use alternative repositories if GitHub is rate limiting.
> Adding alternative trivy repos.
