spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/LocalAppDeployer.java
- If environment property doesn't have value for `spring.cloud.deployer.count` then check if the definition property has it
- If both don't have it set, then use the default count 1
=> Infer count property from the environment

spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/LocalAppDeployer.java, spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/LocalDeployerProperties.java
Replaced hard coded set of env variables with a configurable string array of regular expressions for var retention.
The check for Windows to include `TMP` was removed for simplicity - is this required or can we include this on other platforms?
This fixes https://github.com/spring-cloud/spring-cloud-deployer/issues/25.
=> Configurable regex for env var retention

spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/AbstractDeployerSupport.java, spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/LocalAppDeployer.java, spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/LocalTaskLauncher.java, spring-cloud-deployer-local/src/test/java/org/springframework/cloud/deployer/spi/local/LocalAppDeployerIntegrationTests.java, spring-cloud-deployer-spi/src/main/java/org/springframework/cloud/deployer/spi/core/AppDeploymentRequest.java
- AppDeploymentRequest now has commandlineArguments
as Set.
- Small refactoring by adding shared AbstractDeployerSupport
for LocalAppDeployer and LocalTaskLauncher.
- Only supports arbitrary java arguments, not options which
should go between `java` and `-jar`. Arguments are placed after
`java -jar awesomefat.jar` as is.
- We don't have a proper way to test argument passing
as we can't read stdout/stderr in tests, otherwise
using i.e. timestamp task would be easy to verify
correct passing via its `format` option.
- Actual integration in a dataflow side will be done
in github.com/spring-cloud/spring-cloud-dataflow/issues/503.
- Fixes #20
=> Add option for command line args

spring-cloud-deployer-resource-support/src/main/java/org/springframework/cloud/deployer/resource/support/DelegatingResourceLoader.java
- Add better catch in DelegatingResourceLoader
for existsAsFile().
- Fixes #49
=> Guard getFile with all exceptions

spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/AbstractDeployerSupport.java, spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/LocalAppDeployer.java, spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/LocalTaskLauncher.java
- Refactor LocalTaskLauncher to use same
ProcessBuilder concepts than LocalAppDeployer.
- Moved some common functionality into a parent
AbstractDeployerSupport.
- Fixes #42
=> LocalTaskLauncher not using parent env

spring-cloud-deployer-resource-support/src/main/java/org/springframework/cloud/deployer/resource/support/DelegatingResourceLoader.java
Since we now support "empty" or null loaders, a user should be able to use a default constructor.
=> Added default constructor.

spring-cloud-deployer-resource-maven/src/main/java/org/springframework/cloud/deployer/resource/maven/MavenArtifactResolver.java, spring-cloud-deployer-resource-maven/src/main/java/org/springframework/cloud/deployer/resource/maven/MavenProperties.java
=> Additionally resolve pom extension

spring-cloud-deployer-spi/src/main/java/org/springframework/cloud/deployer/spi/task/TaskLauncher.java
This PR should either get merged or deleted.
- Default interface methods for cleanup
and destroy. These are no-op methods as
most impls simply wont need this behaviour.
- Fixes #151
=> Add default TaskLauncher methods

spring-cloud-deployer-resource-support/src/main/java/org/springframework/cloud/deployer/resource/registry/UriRegistryPopulator.java, spring-cloud-deployer-resource-support/src/test/java/org/springframework/cloud/deployer/resource/registry/UriRegistryPopulatorTests.java
Fixes https://github.com/spring-cloud/spring-cloud-deployer/issues/181
Needed by https://github.com/spring-cloud/spring-cloud-dataflow/pull/1145
=> UriRegistryPopulator now takes a Resource. Use static access

mvnw, mvnw.cmd, pom.xml, spring-cloud-deployer-dependencies/pom.xml
This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were switched to an https URL with a 2xx status. While the status was successful, your review is still recommended.
* http://www.apache.org/licenses/LICENSE-2.0 migrated to:  
https://www.apache.org/licenses/LICENSE-2.0 ([https](https://www.apache.org/licenses/LICENSE-2.0) result 200).
* http://repo.spring.io/libs-milestone-local migrated to:  
https://repo.spring.io/libs-milestone-local ([https](https://repo.spring.io/libs-milestone-local) result 302).
* http://repo.spring.io/libs-snapshot-local migrated to:  
https://repo.spring.io/libs-snapshot-local ([https](https://repo.spring.io/libs-snapshot-local) …
=> URL Cleanup

spring-cloud-deployer-spi-test/src/main/java/org/springframework/cloud/deployer/spi/test/AbstractAppDeployerIntegrationTests.java, spring-cloud-deployer-spi-test/src/main/java/org/springframework/cloud/deployer/spi/test/AbstractTaskLauncherIntegrationTests.java, spring-cloud-deployer-spi/src/main/java/org/springframework/cloud/deployer/spi/app/AppDeployer.java, spring-cloud-deployer-spi/src/main/java/org/springframework/cloud/deployer/spi/task/TaskLauncher.java
- This SPI method lets the AppDeployer/TaskLauncher implementations to retrieve application logs based on the platform
Resolves #306
=> Add getLog SPI to AppDeployer/TaskLauncher

spring-cloud-deployer-spi/src/main/java/org/springframework/cloud/deployer/spi/app/AppDeployer.java, spring-cloud-deployer-spi/src/main/java/org/springframework/cloud/deployer/spi/task/TaskLauncher.java, spring-cloud-deployer-spi/src/test/java/org/springframework/cloud/deployer/spi/app/AppDeployerTests.java, spring-cloud-deployer-spi/src/test/java/org/springframework/cloud/deployer/spi/app/RuntimeEnvironmentInfoBuilderTests.java, spring-cloud-deployer-spi/src/test/java/org/springframework/cloud/deployer/spi/task/TaskLauncherTests.java
- In both the AppDeployer/TaskLauncher SPI interfaces, adda default method for `getLog` which throws the UnsupportedOperationException
- Add tests
Resolves #315
=> Add default method for getLog

spring-cloud-deployer-spi-test/src/main/java/org/springframework/cloud/deployer/spi/test/AbstractAppDeployerIntegrationTests.java, spring-cloud-deployer-spi-test/src/main/java/org/springframework/cloud/deployer/spi/test/AppCountMatcher.java
- Add AppCountMatcher class
- Add AbstractAppDeployerIntegrationTests#appInstanceCount helper method
- Update doScaleTest to use the eventually(appInstanceCount(is(DESIRED_COUNT))) check.
Resolves #323
=> Support for eventual app instance count matching

pom.xml
- Change maven and maven resolver deps to 3.6.2 and
1.4.1 respectively.
- Main inpact is that this now removes guava from transitive
deps who need to consume maven resource.
- Fixes #326
=> Upgrade maven deps to latest

pom.xml, spring-cloud-deployer-resource-maven/pom.xml, spring-cloud-deployer-resource-maven/src/main/java/org/springframework/cloud/deployer/resource/maven/MavenArtifactResolver.java, spring-cloud-deployer-resource-maven/src/main/java/org/springframework/cloud/deployer/resource/maven/MavenProperties.java, spring-cloud-deployer-resource-maven/src/main/java/org/springframework/cloud/deployer/resource/maven/StaticWagonConfigurator.java, spring-cloud-deployer-resource-maven/src/main/java/org/springframework/cloud/deployer/resource/maven/StaticWagonProvider.java, spring-cloud-deployer-resource-maven/src/test/java/org/springframework/cloud/deployer/resource/maven/MavenExtension.java, spring-cloud-deployer-resource-maven/src/test/java/org/springframework/cloud/deployer/resource/maven/MavenPropertiesTests.java, spring-cloud-deployer-resource-maven/src/test/java/org/springframework/cloud/deployer/resource/maven/WagonHttpTests.java, spring-cloud-deployer-resource-maven/src/test/resources/application.properties
- Order to support preemptive auth need to add wagon http
as this feature exists only in there.
- Conditionally switch to wagon based http with `maven.use-wagon`
- StaticWagonProvider and StaticWagonConfigurator are a replacement
for similar classes in a maven resolver core which would only work
via Plexux containers which are impossible to use in our code base
as those are mean for real maven dynamic classloading extensions
with real builds.
- We simply do a static configuration to add `HttpWagon` and its
configuration which is mapped from `MavenProperties`
- New MavenExtension junit5 concept to mock http endpoints for maven,
this is something what other tests could use as well.
- Start adding tests for `MavenProperties`.
- Generic list of settings include httpclient params and headers, …
=> Add wagon based http transport

pom.xml, spring-cloud-deployer-resource-maven/pom.xml
Ensure commons-io:2.7 is resolved regardless of which dependency is included. 
This resolves https://nvd.nist.gov/vuln/detail/CVE-2021-29425
=> Ensure commons-io:2.7 is resolved regardless of which dependency

spring-cloud-deployer-autoconfigure/src/main/resources/META-INF/spring.factories, spring-cloud-deployer-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
It is discussed here: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#changes-to-auto-configuration And is required if 3.x boot apps need to use this project.
=> Migrate spring.factories to autoconfiguration.imports per boot standard

spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesTaskLauncher.java
Avoid duplicate deployment id when multiple tasks launched simultaneously.
Fixes #399
=> Add random number to k8s task deployment id.

spring-cloud-deployer-cloudfoundry/src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/AbstractCloudFoundryTaskLauncher.java, spring-cloud-deployer-cloudfoundry/src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/ApplicationLogAccessor.java, spring-cloud-deployer-cloudfoundry/src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployer.java, spring-cloud-deployer-cloudfoundry/src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryTaskLauncher.java, spring-cloud-deployer-cloudfoundry/src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployerTests.java, spring-cloud-deployer-cloudfoundry/src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryTaskLauncherTests.java
* Filters null envelopes from results.  This was causing the original failure from our update to use the `LogCacheClient`.
* Retrieve GUID from app instance for stream apps. 
* Update `AbstractCloudFoundryTaskLauncher` to add the `app-cf-guid` to the attributes for a task.
* Updated CloudFoundryTaskLauncher to use the `app-cf-guid` from the attributes and use this to retrieve logs from the `LogCacheClient`
* Add Tests
=> Retrieve CF log for tasks and  streams

pom.xml
This commit overrides the logback version in order to fix CVE-2023-6378.
https://github.com/spring-cloud/spring-cloud-dataflow/issues/5593
```
cbono@cbono-a01 spring-cloud-deployer % ./mvnw clean dependency:tree -Dincludes='ch.qos.logback' | grep -e  '1.2.12' | wc -l
16
cbono@cbono-a01 spring-cloud-deployer % ./mvnw clean dependency:tree -Dincludes='ch.qos.logback' | grep -e  '1.2.13' | wc -l
0
```
```
cbono@cbono-a01 spring-cloud-deployer % ./mvnw clean dependency:tree -Dincludes='ch.qos.logback' | grep -e  '1.2.12' | wc -l
0
cbono@cbono-a01 spring-cloud-deployer % ./mvnw clean dependency:tree -Dincludes='ch.qos.logback' | grep -e  '1.2.13' | wc -l
16
```
=> Override logback version to 1.2.13

spring-cloud-deployer-cloudfoundry/src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/ApplicationLogAccessor.java, spring-cloud-deployer-cloudfoundry/src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/ApplicationLogAccessorTests.java
The current log implementation returns the max limit of log envelopes from the start of the log.  However if a log exceeds this maximum the rest of the log is trimmed off.  In this case we retrieve the logs from the tail of the log to the maximum limit of log envelopes.
Also added missing tests for this class.
=> Return the latest logs

spring-cloud-deployer-kubernetes/src/test/java/org/springframework/cloud/deployer/spi/kubernetes/AbstractKubernetesTaskLauncherIntegrationTests.java, spring-cloud-deployer-spi-test/src/main/java/org/springframework/cloud/deployer/spi/scheduler/test/AbstractSchedulerIntegrationJUnit5Tests.java, spring-cloud-deployer-spi-test/src/main/java/org/springframework/cloud/deployer/spi/scheduler/test/AbstractSchedulerIntegrationTests.java, spring-cloud-deployer-spi-test/src/main/java/org/springframework/cloud/deployer/spi/test/AbstractIntegrationJUnit5Tests.java, spring-cloud-deployer-spi-test/src/main/java/org/springframework/cloud/deployer/spi/test/AbstractIntegrationTests.java
During local executions of tests that resolve remote artefacts the throttled download of repo.spring.io causes timeouts. 
Extending the timeouts saves people from going down rabbit holes.
=> Extend timeouts in tests for deployments.

spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/DockerCommandBuilder.java, spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/LocalDeployerProperties.java, spring-cloud-deployer-local/src/test/java/org/springframework/cloud/deployer/spi/local/DockerCommandBuilderTests.java
Hello
I need to use an `host.docker.internal` alias inside docker containers deployed using the Local Deployer to reach services deployed on the host machine for development purposes. Unfortunately this alias does not working out of the box even if a container is attached to a docker network. It requires to pass an `--add-host` to the `docker run` command but Local deployer does not have ability to do it.
So, I created this PR to add ability to define additional host aliases that extends the `DockerCommandBuilder` for proper passing it to the `docker run` command.
=> [Local Deployer] [Docker] Added ability to add additional docker hosts

spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/DeploymentPropertiesResolver.java, spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesDeployerProperties.java, spring-cloud-deployer-kubernetes/src/test/java/org/springframework/cloud/deployer/spi/kubernetes/RunAbstractKubernetesDeployerTests.java
Added k8s requests and limits for ephemeral-storage , hugepages-2Mi and hugepages-1Gi
Fixes #441
=> Added k8s requests and limits

pom.xml, spring-cloud-deployer-cloudfoundry/pom.xml, spring-cloud-deployer-resource-maven/pom.xml
A previous update to commons-compress 1.26.0 introduced a requirement to use commons-io 2.15.1 but there was a version 2.7.x being pulled in by maven resource module. 
This commit adds dependency management to all deployer modules so that these libs stay in sync.
=> Add dep. mgmt. for commons-io and commons-compress

spring-cloud-deployer-kubernetes/pom.xml
`org.hashids:hashids:1.0.1` is 2 years older than 1.0.3
=> Update hashids to 1.0.3

pom.xml
This PR updates Jackson to 2.17.2 as well as moves a few version numbers into Maven properties rather than being specified in the middle of the pom.xml.
=> Put dependency versions in properties

spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/AbstractKubernetesDeployer.java, spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/DeploymentPropertiesResolver.java, spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesDeployerProperties.java, spring-cloud-deployer-kubernetes/src/test/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesAppDeployerTests.java
=> Add relaxed names to nodeSelector property resolution.

spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/AbstractKubernetesDeployer.java, spring-cloud-deployer-kubernetes/src/test/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesAppDeployerTests.java
Volume was only checked on volume-mounts of main container. 
In the case where volumes were defined for use on init-containers or additional-containers it was not added the list of volumes.
Now the volume is checked and added after all containers are known.
Fixes #454
=> Check volume requirement on all containers.

spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/DeploymentPropertiesResolver.java, spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesDeployerProperties.java, spring-cloud-deployer-kubernetes/src/test/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesAppDeployerTests.java
=> Ensure initContainer(s) will configure args provided.

pom.xml, spring-cloud-deployer-cloudfoundry/pom.xml, spring-cloud-deployer-kubernetes/pom.xml, spring-cloud-deployer-local/pom.xml, spring-cloud-deployer-resource-maven/pom.xml, spring-cloud-deployer-spi-test/pom.xml
This commit does the following:
- Removes versions on dependencies that are already managed by boot
- Pulls all version numbers into the root pom.xml
- Removes all unused properties and dependencies
> [!NOTE]
> I reformatted the root pom.xml in commit 2) if you want to see the version changes look at commit 1) first.
=> Cleanup dependencies in pom.xmls

spring-cloud-deployer-cloudfoundry/src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/AbstractCloudFoundryDeployer.java, spring-cloud-deployer-cloudfoundry/src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CfEnvAwareResource.java, spring-cloud-deployer-cloudfoundry/src/main/java/org/springframework/cloud/deployer/spi/scheduler/cloudfoundry/expression/QuartzCronExpression.java, spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/AbstractKubernetesDeployer.java, spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/DefaultContainerFactory.java, spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/DeploymentPropertiesResolver.java, spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesAppDeployer.java, spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesTaskLauncher.java, spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/support/RelaxedNames.java, spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/LocalDeployerUtils.java, spring-cloud-deployer-local/src/test/java/org/springframework/cloud/deployer/spi/local/LocalAppDeployerEnvironmentIntegrationTests.java, src/main/java/org/springframework/cloud/deployer/spi/kubernetes/DefaultContainerFactory.java, src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesAppDeployer.java, src/main/java/org/springframework/cloud/deployer/spi/local/LocalDeployerUtils.java, src/test/java/org/springframework/cloud/deployer/spi/local/LocalAppDeployerEnvironmentIntegrationTests.java
Updated `toLowerCase()` to `toLowerCase(Locale.ROOT)` and `toUpperCase()` to `toUpperCase(Locale.ROOT)`
Fixes #489
=> Updated toLowerCase() and toUpperCase() to use Locale.ROOT

.github/workflows/build-snapshot-worker.yml, .github/workflows/ci.yml, .github/workflows/milestone-worker.yml, .github/workflows/next-dev-version-worker.yml, .github/workflows/release-worker.yml
Updates setup-jfrog-cli to v3 and adds JF_URL env and uses `${{ vars.JF_SERVER_ID }}` for `repo.spring.io`
=> [CI] Update jfrog cli to v3

spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/DeploymentPropertiesResolver.java, spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesDeployerProperties.java, spring-cloud-deployer-kubernetes/src/test/java/org/springframework/cloud/deployer/spi/kubernetes/DefaultContainerFactoryTests.java
Adds missing ephemeral storeagew and hugepages properties.
See #500
Fix missing ephemeral storeage and hugepages properties
Removes deprecated methods in relevant files.
See #500
Fix missing ephemeral storeage and hugepages properties
Fixes test that used deprecated methods.
See #500
Fix missing ephemeral storeage and hugepages properties.
See https://github.com/spring-cloud/spring-cloud-deployer/issues/500
Fix missing ephemeral storeage and hugepages properties.
Fix formatting.
Fix missing ephemeral storeage and hugepages properties.
Revert LimitsResources constructor to deprecated version.
Fix missing ephemeral storeage and hugepages properties.
Revert RequestsResources constructor to previous version and mark as deprecated.
Added extra all args constructors.
Documented and updated …
=> Update PR 501 and apply changes for merge
